version: '3.8'

services:
  api:
    image: mangahash-api:prod
    build:
      context: .
      target: runner
      dockerfile: ./backend/Dockerfile
  crawler:
    image: mangahash-crawler:prod
    build:
      context: .
      target: runner
      dockerfile: ./crawler/Dockerfile
