version: "3.8"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app

    ports:
      - 9090:9090
    tty: true
    command: sh -c 'go mod tidy && air'
