---
apiVersion: v1
kind: Service
metadata:
  name: mangahash-service
spec:
  type: LoadBalancer
  selector:
    app: mangahash-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangahash-api
  labels:
    app: mangahash-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mangahash-api
  template:
    metadata:
      labels:
        app: mangahash-api
    spec:
      containers:
      - name: mangahash-api
        image: mangahash-api:prod
        ports:
        - containerPort: 9090


