// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

type Test struct {
	ID   pgtype.UUID
	Name string
}
